services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    ports:
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: BathroomWatch.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SqlServer: Server=mssql;Database=bathroomwatch;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False
      Jwt__Issuer: BathroomWatch.Api
      Jwt__Audience: BathroomWatch.Web
      Jwt__SigningKey: dev-key-change-this-to-a-long-secret-value
      Cors__AllowedOrigins__0: http://localhost:5173
    ports:
      - "5166:8080"
    depends_on:
      - mssql

volumes:
  sqldata:
