-- Bathroom Watch schema for PostgreSQL
-- Creates ASP.NET Identity tables plus app domain tables.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" text PRIMARY KEY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" text PRIMARY KEY,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    "FullName" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Bathrooms" (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "Name" character varying(200) NOT NULL,
    "Location" character varying(200),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" text,
    CONSTRAINT "FK_Bathrooms_AspNetUsers_CreatedByUserId"
        FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "BathroomReports" (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "BathroomId" uuid NOT NULL,
    "ReporterUserId" text NOT NULL,
    "Status" integer NOT NULL CHECK ("Status" IN (0, 1)),
    "Notes" character varying(500),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_BathroomReports_Bathrooms_BathroomId"
        FOREIGN KEY ("BathroomId") REFERENCES "Bathrooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BathroomReports_AspNetUsers_ReporterUserId"
        FOREIGN KEY ("ReporterUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "BathroomSubscriptions" (
    "BathroomId" uuid NOT NULL,
    "UserId" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BathroomSubscriptions" PRIMARY KEY ("BathroomId", "UserId"),
    CONSTRAINT "FK_BathroomSubscriptions_Bathrooms_BathroomId"
        FOREIGN KEY ("BathroomId") REFERENCES "Bathrooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BathroomSubscriptions_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON "AspNetRoles" ("NormalizedName")
    WHERE "NormalizedName" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId"
    ON "AspNetRoleClaims" ("RoleId");

CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON "AspNetUsers" ("NormalizedUserName")
    WHERE "NormalizedUserName" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId"
    ON "AspNetUserClaims" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId"
    ON "AspNetUserLogins" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"
    ON "AspNetUserRoles" ("RoleId");

CREATE INDEX IF NOT EXISTS "IX_Bathrooms_CreatedByUserId"
    ON "Bathrooms" ("CreatedByUserId");

CREATE INDEX IF NOT EXISTS "IX_BathroomReports_BathroomId_CreatedAtUtc"
    ON "BathroomReports" ("BathroomId", "CreatedAtUtc");

CREATE INDEX IF NOT EXISTS "IX_BathroomReports_ReporterUserId"
    ON "BathroomReports" ("ReporterUserId");

CREATE INDEX IF NOT EXISTS "IX_BathroomSubscriptions_UserId"
    ON "BathroomSubscriptions" ("UserId");

COMMIT;
